# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e8c16131257902dc95d85427bb9874b81dc12e9d0074e478c4a3d7049ee30c56ca503c2d5c617976b60a24e760831a34b375f5e20d7b79a025965ccdd920c7

test:
  secret_key_base: db477d14702c143ae655e0a337b223ff4b540441cebca0c6b4929b06f6c9a9b38033a12ab20f32aa2b720ca4fa44cedfa32b35ebbfbbd3f3346c89a3124296a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
